// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtEkMZMaNnvUBtU-Iyiq_Q2hmHfcBGvT8',
    appId: '1:534421013624:web:bab52e80c62bacf1fe998d',
    messagingSenderId: '534421013624',
    projectId: 'pricer-8e50c',
    authDomain: 'pricer-8e50c.firebaseapp.com',
    storageBucket: 'pricer-8e50c.appspot.com',
    measurementId: 'G-FX97VQVN00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAwyDkgPidgqbuH4qBbYG_JjawadrLdXc',
    appId: '1:534421013624:android:9e7adb981ec89ff5fe998d',
    messagingSenderId: '534421013624',
    projectId: 'pricer-8e50c',
    storageBucket: 'pricer-8e50c.appspot.com',
  );
}
